/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainSchedulerRouteImport } from './routes/(main)/scheduler'
import { Route as mainResourcesRouteImport } from './routes/(main)/resources'
import { Route as mainReceivingRouteImport } from './routes/(main)/receiving'
import { Route as mainParkingRouteImport } from './routes/(main)/parking'
import { Route as mainDispatchRouteImport } from './routes/(main)/dispatch'
import { Route as mainDashboardRouteImport } from './routes/(main)/dashboard'
import { Route as mainAssignedRouteImport } from './routes/(main)/assigned'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainTerminalsSoakingRouteImport } from './routes/(main)/terminals/soaking'
import { Route as mainTerminalsSewingRouteImport } from './routes/(main)/terminals/sewing'
import { Route as mainTerminalsQualityCheckRouteImport } from './routes/(main)/terminals/quality-check'
import { Route as mainTerminalsPostCuttingRouteImport } from './routes/(main)/terminals/post-cutting'
import { Route as mainTerminalsIroningRouteImport } from './routes/(main)/terminals/ironing'
import { Route as mainTerminalsFinishingRouteImport } from './routes/(main)/terminals/finishing'
import { Route as mainTerminalsCuttingRouteImport } from './routes/(main)/terminals/cutting'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainSchedulerRoute = mainSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainResourcesRoute = mainResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainReceivingRoute = mainReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainParkingRoute = mainParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDispatchRoute = mainDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardRoute = mainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAssignedRoute = mainAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => mainRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainTerminalsSoakingRoute = mainTerminalsSoakingRouteImport.update({
  id: '/terminals/soaking',
  path: '/terminals/soaking',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsSewingRoute = mainTerminalsSewingRouteImport.update({
  id: '/terminals/sewing',
  path: '/terminals/sewing',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsQualityCheckRoute =
  mainTerminalsQualityCheckRouteImport.update({
    id: '/terminals/quality-check',
    path: '/terminals/quality-check',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainTerminalsPostCuttingRoute =
  mainTerminalsPostCuttingRouteImport.update({
    id: '/terminals/post-cutting',
    path: '/terminals/post-cutting',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainTerminalsIroningRoute = mainTerminalsIroningRouteImport.update({
  id: '/terminals/ironing',
  path: '/terminals/ironing',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsFinishingRoute = mainTerminalsFinishingRouteImport.update({
  id: '/terminals/finishing',
  path: '/terminals/finishing',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsCuttingRoute = mainTerminalsCuttingRouteImport.update({
  id: '/terminals/cutting',
  path: '/terminals/cutting',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/assigned': typeof mainAssignedRoute
  '/dashboard': typeof mainDashboardRoute
  '/dispatch': typeof mainDispatchRoute
  '/parking': typeof mainParkingRoute
  '/receiving': typeof mainReceivingRoute
  '/resources': typeof mainResourcesRoute
  '/scheduler': typeof mainSchedulerRoute
  '/terminals/cutting': typeof mainTerminalsCuttingRoute
  '/terminals/finishing': typeof mainTerminalsFinishingRoute
  '/terminals/ironing': typeof mainTerminalsIroningRoute
  '/terminals/post-cutting': typeof mainTerminalsPostCuttingRoute
  '/terminals/quality-check': typeof mainTerminalsQualityCheckRoute
  '/terminals/sewing': typeof mainTerminalsSewingRoute
  '/terminals/soaking': typeof mainTerminalsSoakingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/assigned': typeof mainAssignedRoute
  '/dashboard': typeof mainDashboardRoute
  '/dispatch': typeof mainDispatchRoute
  '/parking': typeof mainParkingRoute
  '/receiving': typeof mainReceivingRoute
  '/resources': typeof mainResourcesRoute
  '/scheduler': typeof mainSchedulerRoute
  '/terminals/cutting': typeof mainTerminalsCuttingRoute
  '/terminals/finishing': typeof mainTerminalsFinishingRoute
  '/terminals/ironing': typeof mainTerminalsIroningRoute
  '/terminals/post-cutting': typeof mainTerminalsPostCuttingRoute
  '/terminals/quality-check': typeof mainTerminalsQualityCheckRoute
  '/terminals/sewing': typeof mainTerminalsSewingRoute
  '/terminals/soaking': typeof mainTerminalsSoakingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(main)/assigned': typeof mainAssignedRoute
  '/(main)/dashboard': typeof mainDashboardRoute
  '/(main)/dispatch': typeof mainDispatchRoute
  '/(main)/parking': typeof mainParkingRoute
  '/(main)/receiving': typeof mainReceivingRoute
  '/(main)/resources': typeof mainResourcesRoute
  '/(main)/scheduler': typeof mainSchedulerRoute
  '/(main)/terminals/cutting': typeof mainTerminalsCuttingRoute
  '/(main)/terminals/finishing': typeof mainTerminalsFinishingRoute
  '/(main)/terminals/ironing': typeof mainTerminalsIroningRoute
  '/(main)/terminals/post-cutting': typeof mainTerminalsPostCuttingRoute
  '/(main)/terminals/quality-check': typeof mainTerminalsQualityCheckRoute
  '/(main)/terminals/sewing': typeof mainTerminalsSewingRoute
  '/(main)/terminals/soaking': typeof mainTerminalsSoakingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assigned'
    | '/dashboard'
    | '/dispatch'
    | '/parking'
    | '/receiving'
    | '/resources'
    | '/scheduler'
    | '/terminals/cutting'
    | '/terminals/finishing'
    | '/terminals/ironing'
    | '/terminals/post-cutting'
    | '/terminals/quality-check'
    | '/terminals/sewing'
    | '/terminals/soaking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assigned'
    | '/dashboard'
    | '/dispatch'
    | '/parking'
    | '/receiving'
    | '/resources'
    | '/scheduler'
    | '/terminals/cutting'
    | '/terminals/finishing'
    | '/terminals/ironing'
    | '/terminals/post-cutting'
    | '/terminals/quality-check'
    | '/terminals/sewing'
    | '/terminals/soaking'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(auth)/login'
    | '/(main)/assigned'
    | '/(main)/dashboard'
    | '/(main)/dispatch'
    | '/(main)/parking'
    | '/(main)/receiving'
    | '/(main)/resources'
    | '/(main)/scheduler'
    | '/(main)/terminals/cutting'
    | '/(main)/terminals/finishing'
    | '/(main)/terminals/ironing'
    | '/(main)/terminals/post-cutting'
    | '/(main)/terminals/quality-check'
    | '/(main)/terminals/sewing'
    | '/(main)/terminals/soaking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/scheduler': {
      id: '/(main)/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof mainSchedulerRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/resources': {
      id: '/(main)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof mainResourcesRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/receiving': {
      id: '/(main)/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof mainReceivingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/parking': {
      id: '/(main)/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof mainParkingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dispatch': {
      id: '/(main)/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof mainDispatchRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/assigned': {
      id: '/(main)/assigned'
      path: '/assigned'
      fullPath: '/assigned'
      preLoaderRoute: typeof mainAssignedRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/terminals/soaking': {
      id: '/(main)/terminals/soaking'
      path: '/terminals/soaking'
      fullPath: '/terminals/soaking'
      preLoaderRoute: typeof mainTerminalsSoakingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/sewing': {
      id: '/(main)/terminals/sewing'
      path: '/terminals/sewing'
      fullPath: '/terminals/sewing'
      preLoaderRoute: typeof mainTerminalsSewingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/quality-check': {
      id: '/(main)/terminals/quality-check'
      path: '/terminals/quality-check'
      fullPath: '/terminals/quality-check'
      preLoaderRoute: typeof mainTerminalsQualityCheckRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/post-cutting': {
      id: '/(main)/terminals/post-cutting'
      path: '/terminals/post-cutting'
      fullPath: '/terminals/post-cutting'
      preLoaderRoute: typeof mainTerminalsPostCuttingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/ironing': {
      id: '/(main)/terminals/ironing'
      path: '/terminals/ironing'
      fullPath: '/terminals/ironing'
      preLoaderRoute: typeof mainTerminalsIroningRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/finishing': {
      id: '/(main)/terminals/finishing'
      path: '/terminals/finishing'
      fullPath: '/terminals/finishing'
      preLoaderRoute: typeof mainTerminalsFinishingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/cutting': {
      id: '/(main)/terminals/cutting'
      path: '/terminals/cutting'
      fullPath: '/terminals/cutting'
      preLoaderRoute: typeof mainTerminalsCuttingRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainAssignedRoute: typeof mainAssignedRoute
  mainDashboardRoute: typeof mainDashboardRoute
  mainDispatchRoute: typeof mainDispatchRoute
  mainParkingRoute: typeof mainParkingRoute
  mainReceivingRoute: typeof mainReceivingRoute
  mainResourcesRoute: typeof mainResourcesRoute
  mainSchedulerRoute: typeof mainSchedulerRoute
  mainTerminalsCuttingRoute: typeof mainTerminalsCuttingRoute
  mainTerminalsFinishingRoute: typeof mainTerminalsFinishingRoute
  mainTerminalsIroningRoute: typeof mainTerminalsIroningRoute
  mainTerminalsPostCuttingRoute: typeof mainTerminalsPostCuttingRoute
  mainTerminalsQualityCheckRoute: typeof mainTerminalsQualityCheckRoute
  mainTerminalsSewingRoute: typeof mainTerminalsSewingRoute
  mainTerminalsSoakingRoute: typeof mainTerminalsSoakingRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAssignedRoute: mainAssignedRoute,
  mainDashboardRoute: mainDashboardRoute,
  mainDispatchRoute: mainDispatchRoute,
  mainParkingRoute: mainParkingRoute,
  mainReceivingRoute: mainReceivingRoute,
  mainResourcesRoute: mainResourcesRoute,
  mainSchedulerRoute: mainSchedulerRoute,
  mainTerminalsCuttingRoute: mainTerminalsCuttingRoute,
  mainTerminalsFinishingRoute: mainTerminalsFinishingRoute,
  mainTerminalsIroningRoute: mainTerminalsIroningRoute,
  mainTerminalsPostCuttingRoute: mainTerminalsPostCuttingRoute,
  mainTerminalsQualityCheckRoute: mainTerminalsQualityCheckRoute,
  mainTerminalsSewingRoute: mainTerminalsSewingRoute,
  mainTerminalsSoakingRoute: mainTerminalsSoakingRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
