/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainTeamRouteImport } from './routes/(main)/team'
import { Route as mainSchedulerRouteImport } from './routes/(main)/scheduler'
import { Route as mainReceivingRouteImport } from './routes/(main)/receiving'
import { Route as mainProfileRouteImport } from './routes/(main)/profile'
import { Route as mainPricingRouteImport } from './routes/(main)/pricing'
import { Route as mainParkingRouteImport } from './routes/(main)/parking'
import { Route as mainNotificationsRouteImport } from './routes/(main)/notifications'
import { Route as mainDispatchRouteImport } from './routes/(main)/dispatch'
import { Route as mainDashboardRouteImport } from './routes/(main)/dashboard'
import { Route as mainCompletedRouteImport } from './routes/(main)/completed'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainAssignedRouteRouteImport } from './routes/(main)/assigned/route'
import { Route as mainUsersIndexRouteImport } from './routes/(main)/users/index'
import { Route as mainPerformanceIndexRouteImport } from './routes/(main)/performance/index'
import { Route as mainAssignedIndexRouteImport } from './routes/(main)/assigned/index'
import { Route as mainUsersUserIdRouteImport } from './routes/(main)/users/$userId'
import { Route as mainTerminalsSoakingRouteImport } from './routes/(main)/terminals/soaking'
import { Route as mainTerminalsSewingRouteImport } from './routes/(main)/terminals/sewing'
import { Route as mainTerminalsQualityCheckRouteImport } from './routes/(main)/terminals/quality-check'
import { Route as mainTerminalsPostCuttingRouteImport } from './routes/(main)/terminals/post-cutting'
import { Route as mainTerminalsIroningRouteImport } from './routes/(main)/terminals/ironing'
import { Route as mainTerminalsFinishingRouteImport } from './routes/(main)/terminals/finishing'
import { Route as mainTerminalsCuttingRouteImport } from './routes/(main)/terminals/cutting'
import { Route as mainStoreStockReportRouteImport } from './routes/(main)/store/stock-report'
import { Route as mainStoreSendToShopRouteImport } from './routes/(main)/store/send-to-shop'
import { Route as mainStoreRequestDeliveryRouteImport } from './routes/(main)/store/request-delivery'
import { Route as mainStoreReceivingDeliveriesRouteImport } from './routes/(main)/store/receiving-deliveries'
import { Route as mainStoreInventoryRouteImport } from './routes/(main)/store/inventory'
import { Route as mainStoreApproveRequestsRouteImport } from './routes/(main)/store/approve-requests'
import { Route as mainAssignedOrderIdRouteImport } from './routes/(main)/assigned/$orderId'
import { Route as mainTerminalsGarmentGarmentIdRouteImport } from './routes/(main)/terminals/garment.$garmentId'
import { Route as mainPerformanceWorkerWorkerNameRouteImport } from './routes/(main)/performance/worker.$workerName'
import { Route as mainAssignedGarmentGarmentIdRouteImport } from './routes/(main)/assigned/garment.$garmentId'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainTeamRoute = mainTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainSchedulerRoute = mainSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainReceivingRoute = mainReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainProfileRoute = mainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPricingRoute = mainPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainParkingRoute = mainParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainNotificationsRoute = mainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDispatchRoute = mainDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardRoute = mainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainCompletedRoute = mainCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => mainRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAssignedRouteRoute = mainAssignedRouteRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainUsersIndexRoute = mainUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainPerformanceIndexRoute = mainPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAssignedIndexRoute = mainAssignedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainAssignedRouteRoute,
} as any)
const mainUsersUserIdRoute = mainUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsSoakingRoute = mainTerminalsSoakingRouteImport.update({
  id: '/terminals/soaking',
  path: '/terminals/soaking',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsSewingRoute = mainTerminalsSewingRouteImport.update({
  id: '/terminals/sewing',
  path: '/terminals/sewing',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsQualityCheckRoute =
  mainTerminalsQualityCheckRouteImport.update({
    id: '/terminals/quality-check',
    path: '/terminals/quality-check',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainTerminalsPostCuttingRoute =
  mainTerminalsPostCuttingRouteImport.update({
    id: '/terminals/post-cutting',
    path: '/terminals/post-cutting',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainTerminalsIroningRoute = mainTerminalsIroningRouteImport.update({
  id: '/terminals/ironing',
  path: '/terminals/ironing',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsFinishingRoute = mainTerminalsFinishingRouteImport.update({
  id: '/terminals/finishing',
  path: '/terminals/finishing',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTerminalsCuttingRoute = mainTerminalsCuttingRouteImport.update({
  id: '/terminals/cutting',
  path: '/terminals/cutting',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainStoreStockReportRoute = mainStoreStockReportRouteImport.update({
  id: '/store/stock-report',
  path: '/store/stock-report',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainStoreSendToShopRoute = mainStoreSendToShopRouteImport.update({
  id: '/store/send-to-shop',
  path: '/store/send-to-shop',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainStoreRequestDeliveryRoute =
  mainStoreRequestDeliveryRouteImport.update({
    id: '/store/request-delivery',
    path: '/store/request-delivery',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainStoreReceivingDeliveriesRoute =
  mainStoreReceivingDeliveriesRouteImport.update({
    id: '/store/receiving-deliveries',
    path: '/store/receiving-deliveries',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainStoreInventoryRoute = mainStoreInventoryRouteImport.update({
  id: '/store/inventory',
  path: '/store/inventory',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainStoreApproveRequestsRoute =
  mainStoreApproveRequestsRouteImport.update({
    id: '/store/approve-requests',
    path: '/store/approve-requests',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainAssignedOrderIdRoute = mainAssignedOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => mainAssignedRouteRoute,
} as any)
const mainTerminalsGarmentGarmentIdRoute =
  mainTerminalsGarmentGarmentIdRouteImport.update({
    id: '/terminals/garment/$garmentId',
    path: '/terminals/garment/$garmentId',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainPerformanceWorkerWorkerNameRoute =
  mainPerformanceWorkerWorkerNameRouteImport.update({
    id: '/performance/worker/$workerName',
    path: '/performance/worker/$workerName',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainAssignedGarmentGarmentIdRoute =
  mainAssignedGarmentGarmentIdRouteImport.update({
    id: '/garment/$garmentId',
    path: '/garment/$garmentId',
    getParentRoute: () => mainAssignedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assigned': typeof mainAssignedRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/completed': typeof mainCompletedRoute
  '/dashboard': typeof mainDashboardRoute
  '/dispatch': typeof mainDispatchRoute
  '/notifications': typeof mainNotificationsRoute
  '/parking': typeof mainParkingRoute
  '/pricing': typeof mainPricingRoute
  '/profile': typeof mainProfileRoute
  '/receiving': typeof mainReceivingRoute
  '/scheduler': typeof mainSchedulerRoute
  '/team': typeof mainTeamRoute
  '/assigned/$orderId': typeof mainAssignedOrderIdRoute
  '/store/approve-requests': typeof mainStoreApproveRequestsRoute
  '/store/inventory': typeof mainStoreInventoryRoute
  '/store/receiving-deliveries': typeof mainStoreReceivingDeliveriesRoute
  '/store/request-delivery': typeof mainStoreRequestDeliveryRoute
  '/store/send-to-shop': typeof mainStoreSendToShopRoute
  '/store/stock-report': typeof mainStoreStockReportRoute
  '/terminals/cutting': typeof mainTerminalsCuttingRoute
  '/terminals/finishing': typeof mainTerminalsFinishingRoute
  '/terminals/ironing': typeof mainTerminalsIroningRoute
  '/terminals/post-cutting': typeof mainTerminalsPostCuttingRoute
  '/terminals/quality-check': typeof mainTerminalsQualityCheckRoute
  '/terminals/sewing': typeof mainTerminalsSewingRoute
  '/terminals/soaking': typeof mainTerminalsSoakingRoute
  '/users/$userId': typeof mainUsersUserIdRoute
  '/assigned/': typeof mainAssignedIndexRoute
  '/performance/': typeof mainPerformanceIndexRoute
  '/users/': typeof mainUsersIndexRoute
  '/assigned/garment/$garmentId': typeof mainAssignedGarmentGarmentIdRoute
  '/performance/worker/$workerName': typeof mainPerformanceWorkerWorkerNameRoute
  '/terminals/garment/$garmentId': typeof mainTerminalsGarmentGarmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/completed': typeof mainCompletedRoute
  '/dashboard': typeof mainDashboardRoute
  '/dispatch': typeof mainDispatchRoute
  '/notifications': typeof mainNotificationsRoute
  '/parking': typeof mainParkingRoute
  '/pricing': typeof mainPricingRoute
  '/profile': typeof mainProfileRoute
  '/receiving': typeof mainReceivingRoute
  '/scheduler': typeof mainSchedulerRoute
  '/team': typeof mainTeamRoute
  '/assigned/$orderId': typeof mainAssignedOrderIdRoute
  '/store/approve-requests': typeof mainStoreApproveRequestsRoute
  '/store/inventory': typeof mainStoreInventoryRoute
  '/store/receiving-deliveries': typeof mainStoreReceivingDeliveriesRoute
  '/store/request-delivery': typeof mainStoreRequestDeliveryRoute
  '/store/send-to-shop': typeof mainStoreSendToShopRoute
  '/store/stock-report': typeof mainStoreStockReportRoute
  '/terminals/cutting': typeof mainTerminalsCuttingRoute
  '/terminals/finishing': typeof mainTerminalsFinishingRoute
  '/terminals/ironing': typeof mainTerminalsIroningRoute
  '/terminals/post-cutting': typeof mainTerminalsPostCuttingRoute
  '/terminals/quality-check': typeof mainTerminalsQualityCheckRoute
  '/terminals/sewing': typeof mainTerminalsSewingRoute
  '/terminals/soaking': typeof mainTerminalsSoakingRoute
  '/users/$userId': typeof mainUsersUserIdRoute
  '/assigned': typeof mainAssignedIndexRoute
  '/performance': typeof mainPerformanceIndexRoute
  '/users': typeof mainUsersIndexRoute
  '/assigned/garment/$garmentId': typeof mainAssignedGarmentGarmentIdRoute
  '/performance/worker/$workerName': typeof mainPerformanceWorkerWorkerNameRoute
  '/terminals/garment/$garmentId': typeof mainTerminalsGarmentGarmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/assigned': typeof mainAssignedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(main)/completed': typeof mainCompletedRoute
  '/(main)/dashboard': typeof mainDashboardRoute
  '/(main)/dispatch': typeof mainDispatchRoute
  '/(main)/notifications': typeof mainNotificationsRoute
  '/(main)/parking': typeof mainParkingRoute
  '/(main)/pricing': typeof mainPricingRoute
  '/(main)/profile': typeof mainProfileRoute
  '/(main)/receiving': typeof mainReceivingRoute
  '/(main)/scheduler': typeof mainSchedulerRoute
  '/(main)/team': typeof mainTeamRoute
  '/(main)/assigned/$orderId': typeof mainAssignedOrderIdRoute
  '/(main)/store/approve-requests': typeof mainStoreApproveRequestsRoute
  '/(main)/store/inventory': typeof mainStoreInventoryRoute
  '/(main)/store/receiving-deliveries': typeof mainStoreReceivingDeliveriesRoute
  '/(main)/store/request-delivery': typeof mainStoreRequestDeliveryRoute
  '/(main)/store/send-to-shop': typeof mainStoreSendToShopRoute
  '/(main)/store/stock-report': typeof mainStoreStockReportRoute
  '/(main)/terminals/cutting': typeof mainTerminalsCuttingRoute
  '/(main)/terminals/finishing': typeof mainTerminalsFinishingRoute
  '/(main)/terminals/ironing': typeof mainTerminalsIroningRoute
  '/(main)/terminals/post-cutting': typeof mainTerminalsPostCuttingRoute
  '/(main)/terminals/quality-check': typeof mainTerminalsQualityCheckRoute
  '/(main)/terminals/sewing': typeof mainTerminalsSewingRoute
  '/(main)/terminals/soaking': typeof mainTerminalsSoakingRoute
  '/(main)/users/$userId': typeof mainUsersUserIdRoute
  '/(main)/assigned/': typeof mainAssignedIndexRoute
  '/(main)/performance/': typeof mainPerformanceIndexRoute
  '/(main)/users/': typeof mainUsersIndexRoute
  '/(main)/assigned/garment/$garmentId': typeof mainAssignedGarmentGarmentIdRoute
  '/(main)/performance/worker/$workerName': typeof mainPerformanceWorkerWorkerNameRoute
  '/(main)/terminals/garment/$garmentId': typeof mainTerminalsGarmentGarmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assigned'
    | '/login'
    | '/completed'
    | '/dashboard'
    | '/dispatch'
    | '/notifications'
    | '/parking'
    | '/pricing'
    | '/profile'
    | '/receiving'
    | '/scheduler'
    | '/team'
    | '/assigned/$orderId'
    | '/store/approve-requests'
    | '/store/inventory'
    | '/store/receiving-deliveries'
    | '/store/request-delivery'
    | '/store/send-to-shop'
    | '/store/stock-report'
    | '/terminals/cutting'
    | '/terminals/finishing'
    | '/terminals/ironing'
    | '/terminals/post-cutting'
    | '/terminals/quality-check'
    | '/terminals/sewing'
    | '/terminals/soaking'
    | '/users/$userId'
    | '/assigned/'
    | '/performance/'
    | '/users/'
    | '/assigned/garment/$garmentId'
    | '/performance/worker/$workerName'
    | '/terminals/garment/$garmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/completed'
    | '/dashboard'
    | '/dispatch'
    | '/notifications'
    | '/parking'
    | '/pricing'
    | '/profile'
    | '/receiving'
    | '/scheduler'
    | '/team'
    | '/assigned/$orderId'
    | '/store/approve-requests'
    | '/store/inventory'
    | '/store/receiving-deliveries'
    | '/store/request-delivery'
    | '/store/send-to-shop'
    | '/store/stock-report'
    | '/terminals/cutting'
    | '/terminals/finishing'
    | '/terminals/ironing'
    | '/terminals/post-cutting'
    | '/terminals/quality-check'
    | '/terminals/sewing'
    | '/terminals/soaking'
    | '/users/$userId'
    | '/assigned'
    | '/performance'
    | '/users'
    | '/assigned/garment/$garmentId'
    | '/performance/worker/$workerName'
    | '/terminals/garment/$garmentId'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(main)/assigned'
    | '/(auth)/login'
    | '/(main)/completed'
    | '/(main)/dashboard'
    | '/(main)/dispatch'
    | '/(main)/notifications'
    | '/(main)/parking'
    | '/(main)/pricing'
    | '/(main)/profile'
    | '/(main)/receiving'
    | '/(main)/scheduler'
    | '/(main)/team'
    | '/(main)/assigned/$orderId'
    | '/(main)/store/approve-requests'
    | '/(main)/store/inventory'
    | '/(main)/store/receiving-deliveries'
    | '/(main)/store/request-delivery'
    | '/(main)/store/send-to-shop'
    | '/(main)/store/stock-report'
    | '/(main)/terminals/cutting'
    | '/(main)/terminals/finishing'
    | '/(main)/terminals/ironing'
    | '/(main)/terminals/post-cutting'
    | '/(main)/terminals/quality-check'
    | '/(main)/terminals/sewing'
    | '/(main)/terminals/soaking'
    | '/(main)/users/$userId'
    | '/(main)/assigned/'
    | '/(main)/performance/'
    | '/(main)/users/'
    | '/(main)/assigned/garment/$garmentId'
    | '/(main)/performance/worker/$workerName'
    | '/(main)/terminals/garment/$garmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/team': {
      id: '/(main)/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof mainTeamRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/scheduler': {
      id: '/(main)/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof mainSchedulerRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/receiving': {
      id: '/(main)/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof mainReceivingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/profile': {
      id: '/(main)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof mainProfileRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/pricing': {
      id: '/(main)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof mainPricingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/parking': {
      id: '/(main)/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof mainParkingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/notifications': {
      id: '/(main)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof mainNotificationsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dispatch': {
      id: '/(main)/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof mainDispatchRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/completed': {
      id: '/(main)/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof mainCompletedRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/assigned': {
      id: '/(main)/assigned'
      path: '/assigned'
      fullPath: '/assigned'
      preLoaderRoute: typeof mainAssignedRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/users/': {
      id: '/(main)/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof mainUsersIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/performance/': {
      id: '/(main)/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof mainPerformanceIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/assigned/': {
      id: '/(main)/assigned/'
      path: '/'
      fullPath: '/assigned/'
      preLoaderRoute: typeof mainAssignedIndexRouteImport
      parentRoute: typeof mainAssignedRouteRoute
    }
    '/(main)/users/$userId': {
      id: '/(main)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof mainUsersUserIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/soaking': {
      id: '/(main)/terminals/soaking'
      path: '/terminals/soaking'
      fullPath: '/terminals/soaking'
      preLoaderRoute: typeof mainTerminalsSoakingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/sewing': {
      id: '/(main)/terminals/sewing'
      path: '/terminals/sewing'
      fullPath: '/terminals/sewing'
      preLoaderRoute: typeof mainTerminalsSewingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/quality-check': {
      id: '/(main)/terminals/quality-check'
      path: '/terminals/quality-check'
      fullPath: '/terminals/quality-check'
      preLoaderRoute: typeof mainTerminalsQualityCheckRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/post-cutting': {
      id: '/(main)/terminals/post-cutting'
      path: '/terminals/post-cutting'
      fullPath: '/terminals/post-cutting'
      preLoaderRoute: typeof mainTerminalsPostCuttingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/ironing': {
      id: '/(main)/terminals/ironing'
      path: '/terminals/ironing'
      fullPath: '/terminals/ironing'
      preLoaderRoute: typeof mainTerminalsIroningRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/finishing': {
      id: '/(main)/terminals/finishing'
      path: '/terminals/finishing'
      fullPath: '/terminals/finishing'
      preLoaderRoute: typeof mainTerminalsFinishingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/terminals/cutting': {
      id: '/(main)/terminals/cutting'
      path: '/terminals/cutting'
      fullPath: '/terminals/cutting'
      preLoaderRoute: typeof mainTerminalsCuttingRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/store/stock-report': {
      id: '/(main)/store/stock-report'
      path: '/store/stock-report'
      fullPath: '/store/stock-report'
      preLoaderRoute: typeof mainStoreStockReportRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/store/send-to-shop': {
      id: '/(main)/store/send-to-shop'
      path: '/store/send-to-shop'
      fullPath: '/store/send-to-shop'
      preLoaderRoute: typeof mainStoreSendToShopRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/store/request-delivery': {
      id: '/(main)/store/request-delivery'
      path: '/store/request-delivery'
      fullPath: '/store/request-delivery'
      preLoaderRoute: typeof mainStoreRequestDeliveryRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/store/receiving-deliveries': {
      id: '/(main)/store/receiving-deliveries'
      path: '/store/receiving-deliveries'
      fullPath: '/store/receiving-deliveries'
      preLoaderRoute: typeof mainStoreReceivingDeliveriesRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/store/inventory': {
      id: '/(main)/store/inventory'
      path: '/store/inventory'
      fullPath: '/store/inventory'
      preLoaderRoute: typeof mainStoreInventoryRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/store/approve-requests': {
      id: '/(main)/store/approve-requests'
      path: '/store/approve-requests'
      fullPath: '/store/approve-requests'
      preLoaderRoute: typeof mainStoreApproveRequestsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/assigned/$orderId': {
      id: '/(main)/assigned/$orderId'
      path: '/$orderId'
      fullPath: '/assigned/$orderId'
      preLoaderRoute: typeof mainAssignedOrderIdRouteImport
      parentRoute: typeof mainAssignedRouteRoute
    }
    '/(main)/terminals/garment/$garmentId': {
      id: '/(main)/terminals/garment/$garmentId'
      path: '/terminals/garment/$garmentId'
      fullPath: '/terminals/garment/$garmentId'
      preLoaderRoute: typeof mainTerminalsGarmentGarmentIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/performance/worker/$workerName': {
      id: '/(main)/performance/worker/$workerName'
      path: '/performance/worker/$workerName'
      fullPath: '/performance/worker/$workerName'
      preLoaderRoute: typeof mainPerformanceWorkerWorkerNameRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/assigned/garment/$garmentId': {
      id: '/(main)/assigned/garment/$garmentId'
      path: '/garment/$garmentId'
      fullPath: '/assigned/garment/$garmentId'
      preLoaderRoute: typeof mainAssignedGarmentGarmentIdRouteImport
      parentRoute: typeof mainAssignedRouteRoute
    }
  }
}

interface mainAssignedRouteRouteChildren {
  mainAssignedOrderIdRoute: typeof mainAssignedOrderIdRoute
  mainAssignedIndexRoute: typeof mainAssignedIndexRoute
  mainAssignedGarmentGarmentIdRoute: typeof mainAssignedGarmentGarmentIdRoute
}

const mainAssignedRouteRouteChildren: mainAssignedRouteRouteChildren = {
  mainAssignedOrderIdRoute: mainAssignedOrderIdRoute,
  mainAssignedIndexRoute: mainAssignedIndexRoute,
  mainAssignedGarmentGarmentIdRoute: mainAssignedGarmentGarmentIdRoute,
}

const mainAssignedRouteRouteWithChildren =
  mainAssignedRouteRoute._addFileChildren(mainAssignedRouteRouteChildren)

interface mainRouteRouteChildren {
  mainAssignedRouteRoute: typeof mainAssignedRouteRouteWithChildren
  mainCompletedRoute: typeof mainCompletedRoute
  mainDashboardRoute: typeof mainDashboardRoute
  mainDispatchRoute: typeof mainDispatchRoute
  mainNotificationsRoute: typeof mainNotificationsRoute
  mainParkingRoute: typeof mainParkingRoute
  mainPricingRoute: typeof mainPricingRoute
  mainProfileRoute: typeof mainProfileRoute
  mainReceivingRoute: typeof mainReceivingRoute
  mainSchedulerRoute: typeof mainSchedulerRoute
  mainTeamRoute: typeof mainTeamRoute
  mainStoreApproveRequestsRoute: typeof mainStoreApproveRequestsRoute
  mainStoreInventoryRoute: typeof mainStoreInventoryRoute
  mainStoreReceivingDeliveriesRoute: typeof mainStoreReceivingDeliveriesRoute
  mainStoreRequestDeliveryRoute: typeof mainStoreRequestDeliveryRoute
  mainStoreSendToShopRoute: typeof mainStoreSendToShopRoute
  mainStoreStockReportRoute: typeof mainStoreStockReportRoute
  mainTerminalsCuttingRoute: typeof mainTerminalsCuttingRoute
  mainTerminalsFinishingRoute: typeof mainTerminalsFinishingRoute
  mainTerminalsIroningRoute: typeof mainTerminalsIroningRoute
  mainTerminalsPostCuttingRoute: typeof mainTerminalsPostCuttingRoute
  mainTerminalsQualityCheckRoute: typeof mainTerminalsQualityCheckRoute
  mainTerminalsSewingRoute: typeof mainTerminalsSewingRoute
  mainTerminalsSoakingRoute: typeof mainTerminalsSoakingRoute
  mainUsersUserIdRoute: typeof mainUsersUserIdRoute
  mainPerformanceIndexRoute: typeof mainPerformanceIndexRoute
  mainUsersIndexRoute: typeof mainUsersIndexRoute
  mainPerformanceWorkerWorkerNameRoute: typeof mainPerformanceWorkerWorkerNameRoute
  mainTerminalsGarmentGarmentIdRoute: typeof mainTerminalsGarmentGarmentIdRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAssignedRouteRoute: mainAssignedRouteRouteWithChildren,
  mainCompletedRoute: mainCompletedRoute,
  mainDashboardRoute: mainDashboardRoute,
  mainDispatchRoute: mainDispatchRoute,
  mainNotificationsRoute: mainNotificationsRoute,
  mainParkingRoute: mainParkingRoute,
  mainPricingRoute: mainPricingRoute,
  mainProfileRoute: mainProfileRoute,
  mainReceivingRoute: mainReceivingRoute,
  mainSchedulerRoute: mainSchedulerRoute,
  mainTeamRoute: mainTeamRoute,
  mainStoreApproveRequestsRoute: mainStoreApproveRequestsRoute,
  mainStoreInventoryRoute: mainStoreInventoryRoute,
  mainStoreReceivingDeliveriesRoute: mainStoreReceivingDeliveriesRoute,
  mainStoreRequestDeliveryRoute: mainStoreRequestDeliveryRoute,
  mainStoreSendToShopRoute: mainStoreSendToShopRoute,
  mainStoreStockReportRoute: mainStoreStockReportRoute,
  mainTerminalsCuttingRoute: mainTerminalsCuttingRoute,
  mainTerminalsFinishingRoute: mainTerminalsFinishingRoute,
  mainTerminalsIroningRoute: mainTerminalsIroningRoute,
  mainTerminalsPostCuttingRoute: mainTerminalsPostCuttingRoute,
  mainTerminalsQualityCheckRoute: mainTerminalsQualityCheckRoute,
  mainTerminalsSewingRoute: mainTerminalsSewingRoute,
  mainTerminalsSoakingRoute: mainTerminalsSoakingRoute,
  mainUsersUserIdRoute: mainUsersUserIdRoute,
  mainPerformanceIndexRoute: mainPerformanceIndexRoute,
  mainUsersIndexRoute: mainUsersIndexRoute,
  mainPerformanceWorkerWorkerNameRoute: mainPerformanceWorkerWorkerNameRoute,
  mainTerminalsGarmentGarmentIdRoute: mainTerminalsGarmentGarmentIdRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
