/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainFinanceRouteRouteImport } from './routes/(main)/finance/route'
import { Route as mainTeamIndexRouteImport } from './routes/(main)/team/index'
import { Route as mainOrdersIndexRouteImport } from './routes/(main)/orders/index'
import { Route as mainInventoryIndexRouteImport } from './routes/(main)/inventory/index'
import { Route as mainGarmentsIndexRouteImport } from './routes/(main)/garments/index'
import { Route as mainFinanceIndexRouteImport } from './routes/(main)/finance/index'
import { Route as mainCustomersIndexRouteImport } from './routes/(main)/customers/index'
import { Route as mainOrdersOrderIdRouteImport } from './routes/(main)/orders/$orderId'
import { Route as mainGarmentsGarmentIdRouteImport } from './routes/(main)/garments/$garmentId'
import { Route as mainFinanceTransactionsRouteImport } from './routes/(main)/finance/transactions'
import { Route as mainCustomersCustomerIdRouteImport } from './routes/(main)/customers/$customerId'
import { Route as mainFinanceRegistersIndexRouteImport } from './routes/(main)/finance/registers/index'
import { Route as mainFinancePurchasesIndexRouteImport } from './routes/(main)/finance/purchases/index'
import { Route as mainTeamWorkerWorkerNameRouteImport } from './routes/(main)/team/worker/$workerName'
import { Route as mainTeamStaffUserIdRouteImport } from './routes/(main)/team/staff/$userId'
import { Route as mainTeamPersonUserIdRouteImport } from './routes/(main)/team/person/$userId'
import { Route as mainInventoryItemTypeItemIdRouteImport } from './routes/(main)/inventory/$itemType/$itemId'
import { Route as mainFinanceRegistersSessionIdRouteImport } from './routes/(main)/finance/registers/$sessionId'
import { Route as mainFinancePurchasesPurchaseIdRouteImport } from './routes/(main)/finance/purchases/$purchaseId'

const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainFinanceRouteRoute = mainFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTeamIndexRoute = mainTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainOrdersIndexRoute = mainOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainInventoryIndexRoute = mainInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainGarmentsIndexRoute = mainGarmentsIndexRouteImport.update({
  id: '/garments/',
  path: '/garments/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainFinanceIndexRoute = mainFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainFinanceRouteRoute,
} as any)
const mainCustomersIndexRoute = mainCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainOrdersOrderIdRoute = mainOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainGarmentsGarmentIdRoute = mainGarmentsGarmentIdRouteImport.update({
  id: '/garments/$garmentId',
  path: '/garments/$garmentId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainFinanceTransactionsRoute = mainFinanceTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => mainFinanceRouteRoute,
} as any)
const mainCustomersCustomerIdRoute = mainCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainFinanceRegistersIndexRoute =
  mainFinanceRegistersIndexRouteImport.update({
    id: '/registers/',
    path: '/registers/',
    getParentRoute: () => mainFinanceRouteRoute,
  } as any)
const mainFinancePurchasesIndexRoute =
  mainFinancePurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => mainFinanceRouteRoute,
  } as any)
const mainTeamWorkerWorkerNameRoute =
  mainTeamWorkerWorkerNameRouteImport.update({
    id: '/team/worker/$workerName',
    path: '/team/worker/$workerName',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainTeamStaffUserIdRoute = mainTeamStaffUserIdRouteImport.update({
  id: '/team/staff/$userId',
  path: '/team/staff/$userId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainTeamPersonUserIdRoute = mainTeamPersonUserIdRouteImport.update({
  id: '/team/person/$userId',
  path: '/team/person/$userId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainInventoryItemTypeItemIdRoute =
  mainInventoryItemTypeItemIdRouteImport.update({
    id: '/inventory/$itemType/$itemId',
    path: '/inventory/$itemType/$itemId',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainFinanceRegistersSessionIdRoute =
  mainFinanceRegistersSessionIdRouteImport.update({
    id: '/registers/$sessionId',
    path: '/registers/$sessionId',
    getParentRoute: () => mainFinanceRouteRoute,
  } as any)
const mainFinancePurchasesPurchaseIdRoute =
  mainFinancePurchasesPurchaseIdRouteImport.update({
    id: '/purchases/$purchaseId',
    path: '/purchases/$purchaseId',
    getParentRoute: () => mainFinanceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/access-denied': typeof AccessDeniedRoute
  '/finance': typeof mainFinanceRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/': typeof mainIndexRoute
  '/customers/$customerId': typeof mainCustomersCustomerIdRoute
  '/finance/transactions': typeof mainFinanceTransactionsRoute
  '/garments/$garmentId': typeof mainGarmentsGarmentIdRoute
  '/orders/$orderId': typeof mainOrdersOrderIdRoute
  '/customers/': typeof mainCustomersIndexRoute
  '/finance/': typeof mainFinanceIndexRoute
  '/garments/': typeof mainGarmentsIndexRoute
  '/inventory/': typeof mainInventoryIndexRoute
  '/orders/': typeof mainOrdersIndexRoute
  '/team/': typeof mainTeamIndexRoute
  '/finance/purchases/$purchaseId': typeof mainFinancePurchasesPurchaseIdRoute
  '/finance/registers/$sessionId': typeof mainFinanceRegistersSessionIdRoute
  '/inventory/$itemType/$itemId': typeof mainInventoryItemTypeItemIdRoute
  '/team/person/$userId': typeof mainTeamPersonUserIdRoute
  '/team/staff/$userId': typeof mainTeamStaffUserIdRoute
  '/team/worker/$workerName': typeof mainTeamWorkerWorkerNameRoute
  '/finance/purchases/': typeof mainFinancePurchasesIndexRoute
  '/finance/registers/': typeof mainFinanceRegistersIndexRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof authLoginRoute
  '/': typeof mainIndexRoute
  '/customers/$customerId': typeof mainCustomersCustomerIdRoute
  '/finance/transactions': typeof mainFinanceTransactionsRoute
  '/garments/$garmentId': typeof mainGarmentsGarmentIdRoute
  '/orders/$orderId': typeof mainOrdersOrderIdRoute
  '/customers': typeof mainCustomersIndexRoute
  '/finance': typeof mainFinanceIndexRoute
  '/garments': typeof mainGarmentsIndexRoute
  '/inventory': typeof mainInventoryIndexRoute
  '/orders': typeof mainOrdersIndexRoute
  '/team': typeof mainTeamIndexRoute
  '/finance/purchases/$purchaseId': typeof mainFinancePurchasesPurchaseIdRoute
  '/finance/registers/$sessionId': typeof mainFinanceRegistersSessionIdRoute
  '/inventory/$itemType/$itemId': typeof mainInventoryItemTypeItemIdRoute
  '/team/person/$userId': typeof mainTeamPersonUserIdRoute
  '/team/staff/$userId': typeof mainTeamStaffUserIdRoute
  '/team/worker/$workerName': typeof mainTeamWorkerWorkerNameRoute
  '/finance/purchases': typeof mainFinancePurchasesIndexRoute
  '/finance/registers': typeof mainFinanceRegistersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/(main)/finance': typeof mainFinanceRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/customers/$customerId': typeof mainCustomersCustomerIdRoute
  '/(main)/finance/transactions': typeof mainFinanceTransactionsRoute
  '/(main)/garments/$garmentId': typeof mainGarmentsGarmentIdRoute
  '/(main)/orders/$orderId': typeof mainOrdersOrderIdRoute
  '/(main)/customers/': typeof mainCustomersIndexRoute
  '/(main)/finance/': typeof mainFinanceIndexRoute
  '/(main)/garments/': typeof mainGarmentsIndexRoute
  '/(main)/inventory/': typeof mainInventoryIndexRoute
  '/(main)/orders/': typeof mainOrdersIndexRoute
  '/(main)/team/': typeof mainTeamIndexRoute
  '/(main)/finance/purchases/$purchaseId': typeof mainFinancePurchasesPurchaseIdRoute
  '/(main)/finance/registers/$sessionId': typeof mainFinanceRegistersSessionIdRoute
  '/(main)/inventory/$itemType/$itemId': typeof mainInventoryItemTypeItemIdRoute
  '/(main)/team/person/$userId': typeof mainTeamPersonUserIdRoute
  '/(main)/team/staff/$userId': typeof mainTeamStaffUserIdRoute
  '/(main)/team/worker/$workerName': typeof mainTeamWorkerWorkerNameRoute
  '/(main)/finance/purchases/': typeof mainFinancePurchasesIndexRoute
  '/(main)/finance/registers/': typeof mainFinanceRegistersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/access-denied'
    | '/finance'
    | '/login'
    | '/'
    | '/customers/$customerId'
    | '/finance/transactions'
    | '/garments/$garmentId'
    | '/orders/$orderId'
    | '/customers/'
    | '/finance/'
    | '/garments/'
    | '/inventory/'
    | '/orders/'
    | '/team/'
    | '/finance/purchases/$purchaseId'
    | '/finance/registers/$sessionId'
    | '/inventory/$itemType/$itemId'
    | '/team/person/$userId'
    | '/team/staff/$userId'
    | '/team/worker/$workerName'
    | '/finance/purchases/'
    | '/finance/registers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/login'
    | '/'
    | '/customers/$customerId'
    | '/finance/transactions'
    | '/garments/$garmentId'
    | '/orders/$orderId'
    | '/customers'
    | '/finance'
    | '/garments'
    | '/inventory'
    | '/orders'
    | '/team'
    | '/finance/purchases/$purchaseId'
    | '/finance/registers/$sessionId'
    | '/inventory/$itemType/$itemId'
    | '/team/person/$userId'
    | '/team/staff/$userId'
    | '/team/worker/$workerName'
    | '/finance/purchases'
    | '/finance/registers'
  id:
    | '__root__'
    | '/(main)'
    | '/access-denied'
    | '/(main)/finance'
    | '/(auth)/login'
    | '/(main)/'
    | '/(main)/customers/$customerId'
    | '/(main)/finance/transactions'
    | '/(main)/garments/$garmentId'
    | '/(main)/orders/$orderId'
    | '/(main)/customers/'
    | '/(main)/finance/'
    | '/(main)/garments/'
    | '/(main)/inventory/'
    | '/(main)/orders/'
    | '/(main)/team/'
    | '/(main)/finance/purchases/$purchaseId'
    | '/(main)/finance/registers/$sessionId'
    | '/(main)/inventory/$itemType/$itemId'
    | '/(main)/team/person/$userId'
    | '/(main)/team/staff/$userId'
    | '/(main)/team/worker/$workerName'
    | '/(main)/finance/purchases/'
    | '/(main)/finance/registers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/finance': {
      id: '/(main)/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof mainFinanceRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/team/': {
      id: '/(main)/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof mainTeamIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/orders/': {
      id: '/(main)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof mainOrdersIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/inventory/': {
      id: '/(main)/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof mainInventoryIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/garments/': {
      id: '/(main)/garments/'
      path: '/garments'
      fullPath: '/garments/'
      preLoaderRoute: typeof mainGarmentsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/finance/': {
      id: '/(main)/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof mainFinanceIndexRouteImport
      parentRoute: typeof mainFinanceRouteRoute
    }
    '/(main)/customers/': {
      id: '/(main)/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof mainCustomersIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/orders/$orderId': {
      id: '/(main)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof mainOrdersOrderIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/garments/$garmentId': {
      id: '/(main)/garments/$garmentId'
      path: '/garments/$garmentId'
      fullPath: '/garments/$garmentId'
      preLoaderRoute: typeof mainGarmentsGarmentIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/finance/transactions': {
      id: '/(main)/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof mainFinanceTransactionsRouteImport
      parentRoute: typeof mainFinanceRouteRoute
    }
    '/(main)/customers/$customerId': {
      id: '/(main)/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof mainCustomersCustomerIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/finance/registers/': {
      id: '/(main)/finance/registers/'
      path: '/registers'
      fullPath: '/finance/registers/'
      preLoaderRoute: typeof mainFinanceRegistersIndexRouteImport
      parentRoute: typeof mainFinanceRouteRoute
    }
    '/(main)/finance/purchases/': {
      id: '/(main)/finance/purchases/'
      path: '/purchases'
      fullPath: '/finance/purchases/'
      preLoaderRoute: typeof mainFinancePurchasesIndexRouteImport
      parentRoute: typeof mainFinanceRouteRoute
    }
    '/(main)/team/worker/$workerName': {
      id: '/(main)/team/worker/$workerName'
      path: '/team/worker/$workerName'
      fullPath: '/team/worker/$workerName'
      preLoaderRoute: typeof mainTeamWorkerWorkerNameRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/team/staff/$userId': {
      id: '/(main)/team/staff/$userId'
      path: '/team/staff/$userId'
      fullPath: '/team/staff/$userId'
      preLoaderRoute: typeof mainTeamStaffUserIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/team/person/$userId': {
      id: '/(main)/team/person/$userId'
      path: '/team/person/$userId'
      fullPath: '/team/person/$userId'
      preLoaderRoute: typeof mainTeamPersonUserIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/inventory/$itemType/$itemId': {
      id: '/(main)/inventory/$itemType/$itemId'
      path: '/inventory/$itemType/$itemId'
      fullPath: '/inventory/$itemType/$itemId'
      preLoaderRoute: typeof mainInventoryItemTypeItemIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/finance/registers/$sessionId': {
      id: '/(main)/finance/registers/$sessionId'
      path: '/registers/$sessionId'
      fullPath: '/finance/registers/$sessionId'
      preLoaderRoute: typeof mainFinanceRegistersSessionIdRouteImport
      parentRoute: typeof mainFinanceRouteRoute
    }
    '/(main)/finance/purchases/$purchaseId': {
      id: '/(main)/finance/purchases/$purchaseId'
      path: '/purchases/$purchaseId'
      fullPath: '/finance/purchases/$purchaseId'
      preLoaderRoute: typeof mainFinancePurchasesPurchaseIdRouteImport
      parentRoute: typeof mainFinanceRouteRoute
    }
  }
}

interface mainFinanceRouteRouteChildren {
  mainFinanceTransactionsRoute: typeof mainFinanceTransactionsRoute
  mainFinanceIndexRoute: typeof mainFinanceIndexRoute
  mainFinancePurchasesPurchaseIdRoute: typeof mainFinancePurchasesPurchaseIdRoute
  mainFinanceRegistersSessionIdRoute: typeof mainFinanceRegistersSessionIdRoute
  mainFinancePurchasesIndexRoute: typeof mainFinancePurchasesIndexRoute
  mainFinanceRegistersIndexRoute: typeof mainFinanceRegistersIndexRoute
}

const mainFinanceRouteRouteChildren: mainFinanceRouteRouteChildren = {
  mainFinanceTransactionsRoute: mainFinanceTransactionsRoute,
  mainFinanceIndexRoute: mainFinanceIndexRoute,
  mainFinancePurchasesPurchaseIdRoute: mainFinancePurchasesPurchaseIdRoute,
  mainFinanceRegistersSessionIdRoute: mainFinanceRegistersSessionIdRoute,
  mainFinancePurchasesIndexRoute: mainFinancePurchasesIndexRoute,
  mainFinanceRegistersIndexRoute: mainFinanceRegistersIndexRoute,
}

const mainFinanceRouteRouteWithChildren =
  mainFinanceRouteRoute._addFileChildren(mainFinanceRouteRouteChildren)

interface mainRouteRouteChildren {
  mainFinanceRouteRoute: typeof mainFinanceRouteRouteWithChildren
  mainIndexRoute: typeof mainIndexRoute
  mainCustomersCustomerIdRoute: typeof mainCustomersCustomerIdRoute
  mainGarmentsGarmentIdRoute: typeof mainGarmentsGarmentIdRoute
  mainOrdersOrderIdRoute: typeof mainOrdersOrderIdRoute
  mainCustomersIndexRoute: typeof mainCustomersIndexRoute
  mainGarmentsIndexRoute: typeof mainGarmentsIndexRoute
  mainInventoryIndexRoute: typeof mainInventoryIndexRoute
  mainOrdersIndexRoute: typeof mainOrdersIndexRoute
  mainTeamIndexRoute: typeof mainTeamIndexRoute
  mainInventoryItemTypeItemIdRoute: typeof mainInventoryItemTypeItemIdRoute
  mainTeamPersonUserIdRoute: typeof mainTeamPersonUserIdRoute
  mainTeamStaffUserIdRoute: typeof mainTeamStaffUserIdRoute
  mainTeamWorkerWorkerNameRoute: typeof mainTeamWorkerWorkerNameRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainFinanceRouteRoute: mainFinanceRouteRouteWithChildren,
  mainIndexRoute: mainIndexRoute,
  mainCustomersCustomerIdRoute: mainCustomersCustomerIdRoute,
  mainGarmentsGarmentIdRoute: mainGarmentsGarmentIdRoute,
  mainOrdersOrderIdRoute: mainOrdersOrderIdRoute,
  mainCustomersIndexRoute: mainCustomersIndexRoute,
  mainGarmentsIndexRoute: mainGarmentsIndexRoute,
  mainInventoryIndexRoute: mainInventoryIndexRoute,
  mainOrdersIndexRoute: mainOrdersIndexRoute,
  mainTeamIndexRoute: mainTeamIndexRoute,
  mainInventoryItemTypeItemIdRoute: mainInventoryItemTypeItemIdRoute,
  mainTeamPersonUserIdRoute: mainTeamPersonUserIdRoute,
  mainTeamStaffUserIdRoute: mainTeamStaffUserIdRoute,
  mainTeamWorkerWorkerNameRoute: mainTeamWorkerWorkerNameRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
