/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mainPeopleIndexRouteImport } from './routes/(main)/people/index'
import { Route as mainOrdersIndexRouteImport } from './routes/(main)/orders/index'
import { Route as mainInventoryIndexRouteImport } from './routes/(main)/inventory/index'
import { Route as mainGarmentsIndexRouteImport } from './routes/(main)/garments/index'
import { Route as mainOrdersOrderIdRouteImport } from './routes/(main)/orders/$orderId'
import { Route as mainGarmentsGarmentIdRouteImport } from './routes/(main)/garments/$garmentId'

const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainPeopleIndexRoute = mainPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainOrdersIndexRoute = mainOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainInventoryIndexRoute = mainInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainGarmentsIndexRoute = mainGarmentsIndexRouteImport.update({
  id: '/garments/',
  path: '/garments/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainOrdersOrderIdRoute = mainOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainGarmentsGarmentIdRoute = mainGarmentsGarmentIdRouteImport.update({
  id: '/garments/$garmentId',
  path: '/garments/$garmentId',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof authLoginRoute
  '/': typeof mainIndexRoute
  '/garments/$garmentId': typeof mainGarmentsGarmentIdRoute
  '/orders/$orderId': typeof mainOrdersOrderIdRoute
  '/garments/': typeof mainGarmentsIndexRoute
  '/inventory/': typeof mainInventoryIndexRoute
  '/orders/': typeof mainOrdersIndexRoute
  '/people/': typeof mainPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/login': typeof authLoginRoute
  '/': typeof mainIndexRoute
  '/garments/$garmentId': typeof mainGarmentsGarmentIdRoute
  '/orders/$orderId': typeof mainOrdersOrderIdRoute
  '/garments': typeof mainGarmentsIndexRoute
  '/inventory': typeof mainInventoryIndexRoute
  '/orders': typeof mainOrdersIndexRoute
  '/people': typeof mainPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/(auth)/login': typeof authLoginRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/garments/$garmentId': typeof mainGarmentsGarmentIdRoute
  '/(main)/orders/$orderId': typeof mainOrdersOrderIdRoute
  '/(main)/garments/': typeof mainGarmentsIndexRoute
  '/(main)/inventory/': typeof mainInventoryIndexRoute
  '/(main)/orders/': typeof mainOrdersIndexRoute
  '/(main)/people/': typeof mainPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/access-denied'
    | '/login'
    | '/'
    | '/garments/$garmentId'
    | '/orders/$orderId'
    | '/garments/'
    | '/inventory/'
    | '/orders/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/login'
    | '/'
    | '/garments/$garmentId'
    | '/orders/$orderId'
    | '/garments'
    | '/inventory'
    | '/orders'
    | '/people'
  id:
    | '__root__'
    | '/(main)'
    | '/access-denied'
    | '/(auth)/login'
    | '/(main)/'
    | '/(main)/garments/$garmentId'
    | '/(main)/orders/$orderId'
    | '/(main)/garments/'
    | '/(main)/inventory/'
    | '/(main)/orders/'
    | '/(main)/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/people/': {
      id: '/(main)/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof mainPeopleIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/orders/': {
      id: '/(main)/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof mainOrdersIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/inventory/': {
      id: '/(main)/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof mainInventoryIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/garments/': {
      id: '/(main)/garments/'
      path: '/garments'
      fullPath: '/garments/'
      preLoaderRoute: typeof mainGarmentsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/orders/$orderId': {
      id: '/(main)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof mainOrdersOrderIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/garments/$garmentId': {
      id: '/(main)/garments/$garmentId'
      path: '/garments/$garmentId'
      fullPath: '/garments/$garmentId'
      preLoaderRoute: typeof mainGarmentsGarmentIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainGarmentsGarmentIdRoute: typeof mainGarmentsGarmentIdRoute
  mainOrdersOrderIdRoute: typeof mainOrdersOrderIdRoute
  mainGarmentsIndexRoute: typeof mainGarmentsIndexRoute
  mainInventoryIndexRoute: typeof mainInventoryIndexRoute
  mainOrdersIndexRoute: typeof mainOrdersIndexRoute
  mainPeopleIndexRoute: typeof mainPeopleIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainGarmentsGarmentIdRoute: mainGarmentsGarmentIdRoute,
  mainOrdersOrderIdRoute: mainOrdersOrderIdRoute,
  mainGarmentsIndexRoute: mainGarmentsIndexRoute,
  mainInventoryIndexRoute: mainInventoryIndexRoute,
  mainOrdersIndexRoute: mainOrdersIndexRoute,
  mainPeopleIndexRoute: mainPeopleIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
