/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MainRouteRouteImport } from './routes/$main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainIndexRouteImport } from './routes/$main/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as MainProfileRouteImport } from './routes/$main/profile'
import { Route as MainNotificationsRouteImport } from './routes/$main/notifications'
import { Route as MainCashierRouteImport } from './routes/$main/cashier'
import { Route as MainStoreRouteRouteImport } from './routes/$main/store/route'
import { Route as MainCustomersIndexRouteImport } from './routes/$main/customers/index'
import { Route as MainAppointmentsIndexRouteImport } from './routes/$main/appointments/index'
import { Route as authSakkbaLoginRouteImport } from './routes/(auth)/sakkba/login'
import { Route as authErthLoginRouteImport } from './routes/(auth)/erth/login'
import { Route as MainStoreTransferHistoryRouteImport } from './routes/$main/store/transfer-history'
import { Route as MainStoreStockReportRouteImport } from './routes/$main/store/stock-report'
import { Route as MainStoreRequestDeliveryRouteImport } from './routes/$main/store/request-delivery'
import { Route as MainStoreReceivingDeliveriesRouteImport } from './routes/$main/store/receiving-deliveries'
import { Route as MainStoreEndOfDayReportRouteImport } from './routes/$main/store/end-of-day-report'
import { Route as MainStoreApproveRequestsRouteImport } from './routes/$main/store/approve-requests'
import { Route as MainStoreActiveRequestsRouteImport } from './routes/$main/store/active-requests'
import { Route as MainOrdersOrdersAtShowroomRouteImport } from './routes/$main/orders/orders-at-showroom'
import { Route as MainOrdersOrderHistoryRouteImport } from './routes/$main/orders/order-history'
import { Route as MainOrdersNewWorkOrderRouteImport } from './routes/$main/orders/new-work-order'
import { Route as MainOrdersNewSalesOrderRouteImport } from './routes/$main/orders/new-sales-order'
import { Route as MainOrdersNewAlterationOrderRouteImport } from './routes/$main/orders/new-alteration-order'
import { Route as MainOrdersCustomerProfilesOrdersRouteImport } from './routes/$main/orders/customer-profiles-orders'
import { Route as MainCustomersCustomerIdRouteImport } from './routes/$main/customers/$customerId'
import { Route as MainOrdersOrderManagementUnlinkRouteImport } from './routes/$main/orders/order-management/unlink'
import { Route as MainOrdersOrderManagementReceivingBrovaFinalRouteImport } from './routes/$main/orders/order-management/receiving-brova-final'
import { Route as MainOrdersOrderManagementLinkRouteImport } from './routes/$main/orders/order-management/link'
import { Route as MainOrdersOrderManagementFinalFeedbackRouteImport } from './routes/$main/orders/order-management/final-feedback'
import { Route as MainOrdersOrderManagementDispatchRouteImport } from './routes/$main/orders/order-management/dispatch'
import { Route as MainOrdersOrderManagementChangeOptionsRouteImport } from './routes/$main/orders/order-management/change-options'
import { Route as MainOrdersOrderManagementCancelOrderRouteImport } from './routes/$main/orders/order-management/cancel-order'
import { Route as MainOrdersOrderManagementBrovaFeedbackRouteImport } from './routes/$main/orders/order-management/brova-feedback'
import { Route as MainOrdersOrderManagementAlterationsRouteImport } from './routes/$main/orders/order-management/alterations'
import { Route as MainOrdersOrderManagementFeedbackOrderIdRouteImport } from './routes/$main/orders/order-management/feedback.$orderId'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/$main',
  path: '/$main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainNotificationsRoute = MainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCashierRoute = MainCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainStoreRouteRoute = MainStoreRouteRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCustomersIndexRoute = MainCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAppointmentsIndexRoute = MainAppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => MainRouteRoute,
} as any)
const authSakkbaLoginRoute = authSakkbaLoginRouteImport.update({
  id: '/(auth)/sakkba/login',
  path: '/sakkba/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authErthLoginRoute = authErthLoginRouteImport.update({
  id: '/(auth)/erth/login',
  path: '/erth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainStoreTransferHistoryRoute =
  MainStoreTransferHistoryRouteImport.update({
    id: '/transfer-history',
    path: '/transfer-history',
    getParentRoute: () => MainStoreRouteRoute,
  } as any)
const MainStoreStockReportRoute = MainStoreStockReportRouteImport.update({
  id: '/stock-report',
  path: '/stock-report',
  getParentRoute: () => MainStoreRouteRoute,
} as any)
const MainStoreRequestDeliveryRoute =
  MainStoreRequestDeliveryRouteImport.update({
    id: '/request-delivery',
    path: '/request-delivery',
    getParentRoute: () => MainStoreRouteRoute,
  } as any)
const MainStoreReceivingDeliveriesRoute =
  MainStoreReceivingDeliveriesRouteImport.update({
    id: '/receiving-deliveries',
    path: '/receiving-deliveries',
    getParentRoute: () => MainStoreRouteRoute,
  } as any)
const MainStoreEndOfDayReportRoute = MainStoreEndOfDayReportRouteImport.update({
  id: '/end-of-day-report',
  path: '/end-of-day-report',
  getParentRoute: () => MainStoreRouteRoute,
} as any)
const MainStoreApproveRequestsRoute =
  MainStoreApproveRequestsRouteImport.update({
    id: '/approve-requests',
    path: '/approve-requests',
    getParentRoute: () => MainStoreRouteRoute,
  } as any)
const MainStoreActiveRequestsRoute = MainStoreActiveRequestsRouteImport.update({
  id: '/active-requests',
  path: '/active-requests',
  getParentRoute: () => MainStoreRouteRoute,
} as any)
const MainOrdersOrdersAtShowroomRoute =
  MainOrdersOrdersAtShowroomRouteImport.update({
    id: '/orders/orders-at-showroom',
    path: '/orders/orders-at-showroom',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderHistoryRoute = MainOrdersOrderHistoryRouteImport.update({
  id: '/orders/order-history',
  path: '/orders/order-history',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOrdersNewWorkOrderRoute = MainOrdersNewWorkOrderRouteImport.update({
  id: '/orders/new-work-order',
  path: '/orders/new-work-order',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOrdersNewSalesOrderRoute = MainOrdersNewSalesOrderRouteImport.update({
  id: '/orders/new-sales-order',
  path: '/orders/new-sales-order',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOrdersNewAlterationOrderRoute =
  MainOrdersNewAlterationOrderRouteImport.update({
    id: '/orders/new-alteration-order',
    path: '/orders/new-alteration-order',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersCustomerProfilesOrdersRoute =
  MainOrdersCustomerProfilesOrdersRouteImport.update({
    id: '/orders/customer-profiles-orders',
    path: '/orders/customer-profiles-orders',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainCustomersCustomerIdRoute = MainCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainOrdersOrderManagementUnlinkRoute =
  MainOrdersOrderManagementUnlinkRouteImport.update({
    id: '/orders/order-management/unlink',
    path: '/orders/order-management/unlink',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementReceivingBrovaFinalRoute =
  MainOrdersOrderManagementReceivingBrovaFinalRouteImport.update({
    id: '/orders/order-management/receiving-brova-final',
    path: '/orders/order-management/receiving-brova-final',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementLinkRoute =
  MainOrdersOrderManagementLinkRouteImport.update({
    id: '/orders/order-management/link',
    path: '/orders/order-management/link',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementFinalFeedbackRoute =
  MainOrdersOrderManagementFinalFeedbackRouteImport.update({
    id: '/orders/order-management/final-feedback',
    path: '/orders/order-management/final-feedback',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementDispatchRoute =
  MainOrdersOrderManagementDispatchRouteImport.update({
    id: '/orders/order-management/dispatch',
    path: '/orders/order-management/dispatch',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementChangeOptionsRoute =
  MainOrdersOrderManagementChangeOptionsRouteImport.update({
    id: '/orders/order-management/change-options',
    path: '/orders/order-management/change-options',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementCancelOrderRoute =
  MainOrdersOrderManagementCancelOrderRouteImport.update({
    id: '/orders/order-management/cancel-order',
    path: '/orders/order-management/cancel-order',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementBrovaFeedbackRoute =
  MainOrdersOrderManagementBrovaFeedbackRouteImport.update({
    id: '/orders/order-management/brova-feedback',
    path: '/orders/order-management/brova-feedback',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementAlterationsRoute =
  MainOrdersOrderManagementAlterationsRouteImport.update({
    id: '/orders/order-management/alterations',
    path: '/orders/order-management/alterations',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainOrdersOrderManagementFeedbackOrderIdRoute =
  MainOrdersOrderManagementFeedbackOrderIdRouteImport.update({
    id: '/orders/order-management/feedback/$orderId',
    path: '/orders/order-management/feedback/$orderId',
    getParentRoute: () => MainRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$main': typeof MainRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cashier': typeof CashierRoute
  '/home': typeof HomeRoute
  '/$main/store': typeof MainStoreRouteRouteWithChildren
  '/$main/cashier': typeof MainCashierRoute
  '/$main/notifications': typeof MainNotificationsRoute
  '/$main/profile': typeof MainProfileRoute
  '/login': typeof authLoginRoute
  '/$main/': typeof MainIndexRoute
  '/$main/customers/$customerId': typeof MainCustomersCustomerIdRoute
  '/$main/orders/customer-profiles-orders': typeof MainOrdersCustomerProfilesOrdersRoute
  '/$main/orders/new-alteration-order': typeof MainOrdersNewAlterationOrderRoute
  '/$main/orders/new-sales-order': typeof MainOrdersNewSalesOrderRoute
  '/$main/orders/new-work-order': typeof MainOrdersNewWorkOrderRoute
  '/$main/orders/order-history': typeof MainOrdersOrderHistoryRoute
  '/$main/orders/orders-at-showroom': typeof MainOrdersOrdersAtShowroomRoute
  '/$main/store/active-requests': typeof MainStoreActiveRequestsRoute
  '/$main/store/approve-requests': typeof MainStoreApproveRequestsRoute
  '/$main/store/end-of-day-report': typeof MainStoreEndOfDayReportRoute
  '/$main/store/receiving-deliveries': typeof MainStoreReceivingDeliveriesRoute
  '/$main/store/request-delivery': typeof MainStoreRequestDeliveryRoute
  '/$main/store/stock-report': typeof MainStoreStockReportRoute
  '/$main/store/transfer-history': typeof MainStoreTransferHistoryRoute
  '/erth/login': typeof authErthLoginRoute
  '/sakkba/login': typeof authSakkbaLoginRoute
  '/$main/appointments/': typeof MainAppointmentsIndexRoute
  '/$main/customers/': typeof MainCustomersIndexRoute
  '/$main/orders/order-management/alterations': typeof MainOrdersOrderManagementAlterationsRoute
  '/$main/orders/order-management/brova-feedback': typeof MainOrdersOrderManagementBrovaFeedbackRoute
  '/$main/orders/order-management/cancel-order': typeof MainOrdersOrderManagementCancelOrderRoute
  '/$main/orders/order-management/change-options': typeof MainOrdersOrderManagementChangeOptionsRoute
  '/$main/orders/order-management/dispatch': typeof MainOrdersOrderManagementDispatchRoute
  '/$main/orders/order-management/final-feedback': typeof MainOrdersOrderManagementFinalFeedbackRoute
  '/$main/orders/order-management/link': typeof MainOrdersOrderManagementLinkRoute
  '/$main/orders/order-management/receiving-brova-final': typeof MainOrdersOrderManagementReceivingBrovaFinalRoute
  '/$main/orders/order-management/unlink': typeof MainOrdersOrderManagementUnlinkRoute
  '/$main/orders/order-management/feedback/$orderId': typeof MainOrdersOrderManagementFeedbackOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cashier': typeof CashierRoute
  '/home': typeof HomeRoute
  '/$main/store': typeof MainStoreRouteRouteWithChildren
  '/$main/cashier': typeof MainCashierRoute
  '/$main/notifications': typeof MainNotificationsRoute
  '/$main/profile': typeof MainProfileRoute
  '/login': typeof authLoginRoute
  '/$main': typeof MainIndexRoute
  '/$main/customers/$customerId': typeof MainCustomersCustomerIdRoute
  '/$main/orders/customer-profiles-orders': typeof MainOrdersCustomerProfilesOrdersRoute
  '/$main/orders/new-alteration-order': typeof MainOrdersNewAlterationOrderRoute
  '/$main/orders/new-sales-order': typeof MainOrdersNewSalesOrderRoute
  '/$main/orders/new-work-order': typeof MainOrdersNewWorkOrderRoute
  '/$main/orders/order-history': typeof MainOrdersOrderHistoryRoute
  '/$main/orders/orders-at-showroom': typeof MainOrdersOrdersAtShowroomRoute
  '/$main/store/active-requests': typeof MainStoreActiveRequestsRoute
  '/$main/store/approve-requests': typeof MainStoreApproveRequestsRoute
  '/$main/store/end-of-day-report': typeof MainStoreEndOfDayReportRoute
  '/$main/store/receiving-deliveries': typeof MainStoreReceivingDeliveriesRoute
  '/$main/store/request-delivery': typeof MainStoreRequestDeliveryRoute
  '/$main/store/stock-report': typeof MainStoreStockReportRoute
  '/$main/store/transfer-history': typeof MainStoreTransferHistoryRoute
  '/erth/login': typeof authErthLoginRoute
  '/sakkba/login': typeof authSakkbaLoginRoute
  '/$main/appointments': typeof MainAppointmentsIndexRoute
  '/$main/customers': typeof MainCustomersIndexRoute
  '/$main/orders/order-management/alterations': typeof MainOrdersOrderManagementAlterationsRoute
  '/$main/orders/order-management/brova-feedback': typeof MainOrdersOrderManagementBrovaFeedbackRoute
  '/$main/orders/order-management/cancel-order': typeof MainOrdersOrderManagementCancelOrderRoute
  '/$main/orders/order-management/change-options': typeof MainOrdersOrderManagementChangeOptionsRoute
  '/$main/orders/order-management/dispatch': typeof MainOrdersOrderManagementDispatchRoute
  '/$main/orders/order-management/final-feedback': typeof MainOrdersOrderManagementFinalFeedbackRoute
  '/$main/orders/order-management/link': typeof MainOrdersOrderManagementLinkRoute
  '/$main/orders/order-management/receiving-brova-final': typeof MainOrdersOrderManagementReceivingBrovaFinalRoute
  '/$main/orders/order-management/unlink': typeof MainOrdersOrderManagementUnlinkRoute
  '/$main/orders/order-management/feedback/$orderId': typeof MainOrdersOrderManagementFeedbackOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$main': typeof MainRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cashier': typeof CashierRoute
  '/home': typeof HomeRoute
  '/$main/store': typeof MainStoreRouteRouteWithChildren
  '/$main/cashier': typeof MainCashierRoute
  '/$main/notifications': typeof MainNotificationsRoute
  '/$main/profile': typeof MainProfileRoute
  '/(auth)/login': typeof authLoginRoute
  '/$main/': typeof MainIndexRoute
  '/$main/customers/$customerId': typeof MainCustomersCustomerIdRoute
  '/$main/orders/customer-profiles-orders': typeof MainOrdersCustomerProfilesOrdersRoute
  '/$main/orders/new-alteration-order': typeof MainOrdersNewAlterationOrderRoute
  '/$main/orders/new-sales-order': typeof MainOrdersNewSalesOrderRoute
  '/$main/orders/new-work-order': typeof MainOrdersNewWorkOrderRoute
  '/$main/orders/order-history': typeof MainOrdersOrderHistoryRoute
  '/$main/orders/orders-at-showroom': typeof MainOrdersOrdersAtShowroomRoute
  '/$main/store/active-requests': typeof MainStoreActiveRequestsRoute
  '/$main/store/approve-requests': typeof MainStoreApproveRequestsRoute
  '/$main/store/end-of-day-report': typeof MainStoreEndOfDayReportRoute
  '/$main/store/receiving-deliveries': typeof MainStoreReceivingDeliveriesRoute
  '/$main/store/request-delivery': typeof MainStoreRequestDeliveryRoute
  '/$main/store/stock-report': typeof MainStoreStockReportRoute
  '/$main/store/transfer-history': typeof MainStoreTransferHistoryRoute
  '/(auth)/erth/login': typeof authErthLoginRoute
  '/(auth)/sakkba/login': typeof authSakkbaLoginRoute
  '/$main/appointments/': typeof MainAppointmentsIndexRoute
  '/$main/customers/': typeof MainCustomersIndexRoute
  '/$main/orders/order-management/alterations': typeof MainOrdersOrderManagementAlterationsRoute
  '/$main/orders/order-management/brova-feedback': typeof MainOrdersOrderManagementBrovaFeedbackRoute
  '/$main/orders/order-management/cancel-order': typeof MainOrdersOrderManagementCancelOrderRoute
  '/$main/orders/order-management/change-options': typeof MainOrdersOrderManagementChangeOptionsRoute
  '/$main/orders/order-management/dispatch': typeof MainOrdersOrderManagementDispatchRoute
  '/$main/orders/order-management/final-feedback': typeof MainOrdersOrderManagementFinalFeedbackRoute
  '/$main/orders/order-management/link': typeof MainOrdersOrderManagementLinkRoute
  '/$main/orders/order-management/receiving-brova-final': typeof MainOrdersOrderManagementReceivingBrovaFinalRoute
  '/$main/orders/order-management/unlink': typeof MainOrdersOrderManagementUnlinkRoute
  '/$main/orders/order-management/feedback/$orderId': typeof MainOrdersOrderManagementFeedbackOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$main'
    | '/about'
    | '/cashier'
    | '/home'
    | '/$main/store'
    | '/$main/cashier'
    | '/$main/notifications'
    | '/$main/profile'
    | '/login'
    | '/$main/'
    | '/$main/customers/$customerId'
    | '/$main/orders/customer-profiles-orders'
    | '/$main/orders/new-alteration-order'
    | '/$main/orders/new-sales-order'
    | '/$main/orders/new-work-order'
    | '/$main/orders/order-history'
    | '/$main/orders/orders-at-showroom'
    | '/$main/store/active-requests'
    | '/$main/store/approve-requests'
    | '/$main/store/end-of-day-report'
    | '/$main/store/receiving-deliveries'
    | '/$main/store/request-delivery'
    | '/$main/store/stock-report'
    | '/$main/store/transfer-history'
    | '/erth/login'
    | '/sakkba/login'
    | '/$main/appointments/'
    | '/$main/customers/'
    | '/$main/orders/order-management/alterations'
    | '/$main/orders/order-management/brova-feedback'
    | '/$main/orders/order-management/cancel-order'
    | '/$main/orders/order-management/change-options'
    | '/$main/orders/order-management/dispatch'
    | '/$main/orders/order-management/final-feedback'
    | '/$main/orders/order-management/link'
    | '/$main/orders/order-management/receiving-brova-final'
    | '/$main/orders/order-management/unlink'
    | '/$main/orders/order-management/feedback/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cashier'
    | '/home'
    | '/$main/store'
    | '/$main/cashier'
    | '/$main/notifications'
    | '/$main/profile'
    | '/login'
    | '/$main'
    | '/$main/customers/$customerId'
    | '/$main/orders/customer-profiles-orders'
    | '/$main/orders/new-alteration-order'
    | '/$main/orders/new-sales-order'
    | '/$main/orders/new-work-order'
    | '/$main/orders/order-history'
    | '/$main/orders/orders-at-showroom'
    | '/$main/store/active-requests'
    | '/$main/store/approve-requests'
    | '/$main/store/end-of-day-report'
    | '/$main/store/receiving-deliveries'
    | '/$main/store/request-delivery'
    | '/$main/store/stock-report'
    | '/$main/store/transfer-history'
    | '/erth/login'
    | '/sakkba/login'
    | '/$main/appointments'
    | '/$main/customers'
    | '/$main/orders/order-management/alterations'
    | '/$main/orders/order-management/brova-feedback'
    | '/$main/orders/order-management/cancel-order'
    | '/$main/orders/order-management/change-options'
    | '/$main/orders/order-management/dispatch'
    | '/$main/orders/order-management/final-feedback'
    | '/$main/orders/order-management/link'
    | '/$main/orders/order-management/receiving-brova-final'
    | '/$main/orders/order-management/unlink'
    | '/$main/orders/order-management/feedback/$orderId'
  id:
    | '__root__'
    | '/'
    | '/$main'
    | '/about'
    | '/cashier'
    | '/home'
    | '/$main/store'
    | '/$main/cashier'
    | '/$main/notifications'
    | '/$main/profile'
    | '/(auth)/login'
    | '/$main/'
    | '/$main/customers/$customerId'
    | '/$main/orders/customer-profiles-orders'
    | '/$main/orders/new-alteration-order'
    | '/$main/orders/new-sales-order'
    | '/$main/orders/new-work-order'
    | '/$main/orders/order-history'
    | '/$main/orders/orders-at-showroom'
    | '/$main/store/active-requests'
    | '/$main/store/approve-requests'
    | '/$main/store/end-of-day-report'
    | '/$main/store/receiving-deliveries'
    | '/$main/store/request-delivery'
    | '/$main/store/stock-report'
    | '/$main/store/transfer-history'
    | '/(auth)/erth/login'
    | '/(auth)/sakkba/login'
    | '/$main/appointments/'
    | '/$main/customers/'
    | '/$main/orders/order-management/alterations'
    | '/$main/orders/order-management/brova-feedback'
    | '/$main/orders/order-management/cancel-order'
    | '/$main/orders/order-management/change-options'
    | '/$main/orders/order-management/dispatch'
    | '/$main/orders/order-management/final-feedback'
    | '/$main/orders/order-management/link'
    | '/$main/orders/order-management/receiving-brova-final'
    | '/$main/orders/order-management/unlink'
    | '/$main/orders/order-management/feedback/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CashierRoute: typeof CashierRoute
  HomeRoute: typeof HomeRoute
  authLoginRoute: typeof authLoginRoute
  authErthLoginRoute: typeof authErthLoginRoute
  authSakkbaLoginRoute: typeof authSakkbaLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$main': {
      id: '/$main'
      path: '/$main'
      fullPath: '/$main'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$main/': {
      id: '/$main/'
      path: '/'
      fullPath: '/$main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$main/profile': {
      id: '/$main/profile'
      path: '/profile'
      fullPath: '/$main/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/notifications': {
      id: '/$main/notifications'
      path: '/notifications'
      fullPath: '/$main/notifications'
      preLoaderRoute: typeof MainNotificationsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/cashier': {
      id: '/$main/cashier'
      path: '/cashier'
      fullPath: '/$main/cashier'
      preLoaderRoute: typeof MainCashierRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/store': {
      id: '/$main/store'
      path: '/store'
      fullPath: '/$main/store'
      preLoaderRoute: typeof MainStoreRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/customers/': {
      id: '/$main/customers/'
      path: '/customers'
      fullPath: '/$main/customers/'
      preLoaderRoute: typeof MainCustomersIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/appointments/': {
      id: '/$main/appointments/'
      path: '/appointments'
      fullPath: '/$main/appointments/'
      preLoaderRoute: typeof MainAppointmentsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/(auth)/sakkba/login': {
      id: '/(auth)/sakkba/login'
      path: '/sakkba/login'
      fullPath: '/sakkba/login'
      preLoaderRoute: typeof authSakkbaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/erth/login': {
      id: '/(auth)/erth/login'
      path: '/erth/login'
      fullPath: '/erth/login'
      preLoaderRoute: typeof authErthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$main/store/transfer-history': {
      id: '/$main/store/transfer-history'
      path: '/transfer-history'
      fullPath: '/$main/store/transfer-history'
      preLoaderRoute: typeof MainStoreTransferHistoryRouteImport
      parentRoute: typeof MainStoreRouteRoute
    }
    '/$main/store/stock-report': {
      id: '/$main/store/stock-report'
      path: '/stock-report'
      fullPath: '/$main/store/stock-report'
      preLoaderRoute: typeof MainStoreStockReportRouteImport
      parentRoute: typeof MainStoreRouteRoute
    }
    '/$main/store/request-delivery': {
      id: '/$main/store/request-delivery'
      path: '/request-delivery'
      fullPath: '/$main/store/request-delivery'
      preLoaderRoute: typeof MainStoreRequestDeliveryRouteImport
      parentRoute: typeof MainStoreRouteRoute
    }
    '/$main/store/receiving-deliveries': {
      id: '/$main/store/receiving-deliveries'
      path: '/receiving-deliveries'
      fullPath: '/$main/store/receiving-deliveries'
      preLoaderRoute: typeof MainStoreReceivingDeliveriesRouteImport
      parentRoute: typeof MainStoreRouteRoute
    }
    '/$main/store/end-of-day-report': {
      id: '/$main/store/end-of-day-report'
      path: '/end-of-day-report'
      fullPath: '/$main/store/end-of-day-report'
      preLoaderRoute: typeof MainStoreEndOfDayReportRouteImport
      parentRoute: typeof MainStoreRouteRoute
    }
    '/$main/store/approve-requests': {
      id: '/$main/store/approve-requests'
      path: '/approve-requests'
      fullPath: '/$main/store/approve-requests'
      preLoaderRoute: typeof MainStoreApproveRequestsRouteImport
      parentRoute: typeof MainStoreRouteRoute
    }
    '/$main/store/active-requests': {
      id: '/$main/store/active-requests'
      path: '/active-requests'
      fullPath: '/$main/store/active-requests'
      preLoaderRoute: typeof MainStoreActiveRequestsRouteImport
      parentRoute: typeof MainStoreRouteRoute
    }
    '/$main/orders/orders-at-showroom': {
      id: '/$main/orders/orders-at-showroom'
      path: '/orders/orders-at-showroom'
      fullPath: '/$main/orders/orders-at-showroom'
      preLoaderRoute: typeof MainOrdersOrdersAtShowroomRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-history': {
      id: '/$main/orders/order-history'
      path: '/orders/order-history'
      fullPath: '/$main/orders/order-history'
      preLoaderRoute: typeof MainOrdersOrderHistoryRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/new-work-order': {
      id: '/$main/orders/new-work-order'
      path: '/orders/new-work-order'
      fullPath: '/$main/orders/new-work-order'
      preLoaderRoute: typeof MainOrdersNewWorkOrderRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/new-sales-order': {
      id: '/$main/orders/new-sales-order'
      path: '/orders/new-sales-order'
      fullPath: '/$main/orders/new-sales-order'
      preLoaderRoute: typeof MainOrdersNewSalesOrderRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/new-alteration-order': {
      id: '/$main/orders/new-alteration-order'
      path: '/orders/new-alteration-order'
      fullPath: '/$main/orders/new-alteration-order'
      preLoaderRoute: typeof MainOrdersNewAlterationOrderRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/customer-profiles-orders': {
      id: '/$main/orders/customer-profiles-orders'
      path: '/orders/customer-profiles-orders'
      fullPath: '/$main/orders/customer-profiles-orders'
      preLoaderRoute: typeof MainOrdersCustomerProfilesOrdersRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/customers/$customerId': {
      id: '/$main/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/$main/customers/$customerId'
      preLoaderRoute: typeof MainCustomersCustomerIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/unlink': {
      id: '/$main/orders/order-management/unlink'
      path: '/orders/order-management/unlink'
      fullPath: '/$main/orders/order-management/unlink'
      preLoaderRoute: typeof MainOrdersOrderManagementUnlinkRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/receiving-brova-final': {
      id: '/$main/orders/order-management/receiving-brova-final'
      path: '/orders/order-management/receiving-brova-final'
      fullPath: '/$main/orders/order-management/receiving-brova-final'
      preLoaderRoute: typeof MainOrdersOrderManagementReceivingBrovaFinalRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/link': {
      id: '/$main/orders/order-management/link'
      path: '/orders/order-management/link'
      fullPath: '/$main/orders/order-management/link'
      preLoaderRoute: typeof MainOrdersOrderManagementLinkRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/final-feedback': {
      id: '/$main/orders/order-management/final-feedback'
      path: '/orders/order-management/final-feedback'
      fullPath: '/$main/orders/order-management/final-feedback'
      preLoaderRoute: typeof MainOrdersOrderManagementFinalFeedbackRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/dispatch': {
      id: '/$main/orders/order-management/dispatch'
      path: '/orders/order-management/dispatch'
      fullPath: '/$main/orders/order-management/dispatch'
      preLoaderRoute: typeof MainOrdersOrderManagementDispatchRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/change-options': {
      id: '/$main/orders/order-management/change-options'
      path: '/orders/order-management/change-options'
      fullPath: '/$main/orders/order-management/change-options'
      preLoaderRoute: typeof MainOrdersOrderManagementChangeOptionsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/cancel-order': {
      id: '/$main/orders/order-management/cancel-order'
      path: '/orders/order-management/cancel-order'
      fullPath: '/$main/orders/order-management/cancel-order'
      preLoaderRoute: typeof MainOrdersOrderManagementCancelOrderRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/brova-feedback': {
      id: '/$main/orders/order-management/brova-feedback'
      path: '/orders/order-management/brova-feedback'
      fullPath: '/$main/orders/order-management/brova-feedback'
      preLoaderRoute: typeof MainOrdersOrderManagementBrovaFeedbackRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/alterations': {
      id: '/$main/orders/order-management/alterations'
      path: '/orders/order-management/alterations'
      fullPath: '/$main/orders/order-management/alterations'
      preLoaderRoute: typeof MainOrdersOrderManagementAlterationsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/$main/orders/order-management/feedback/$orderId': {
      id: '/$main/orders/order-management/feedback/$orderId'
      path: '/orders/order-management/feedback/$orderId'
      fullPath: '/$main/orders/order-management/feedback/$orderId'
      preLoaderRoute: typeof MainOrdersOrderManagementFeedbackOrderIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainStoreRouteRouteChildren {
  MainStoreActiveRequestsRoute: typeof MainStoreActiveRequestsRoute
  MainStoreApproveRequestsRoute: typeof MainStoreApproveRequestsRoute
  MainStoreEndOfDayReportRoute: typeof MainStoreEndOfDayReportRoute
  MainStoreReceivingDeliveriesRoute: typeof MainStoreReceivingDeliveriesRoute
  MainStoreRequestDeliveryRoute: typeof MainStoreRequestDeliveryRoute
  MainStoreStockReportRoute: typeof MainStoreStockReportRoute
  MainStoreTransferHistoryRoute: typeof MainStoreTransferHistoryRoute
}

const MainStoreRouteRouteChildren: MainStoreRouteRouteChildren = {
  MainStoreActiveRequestsRoute: MainStoreActiveRequestsRoute,
  MainStoreApproveRequestsRoute: MainStoreApproveRequestsRoute,
  MainStoreEndOfDayReportRoute: MainStoreEndOfDayReportRoute,
  MainStoreReceivingDeliveriesRoute: MainStoreReceivingDeliveriesRoute,
  MainStoreRequestDeliveryRoute: MainStoreRequestDeliveryRoute,
  MainStoreStockReportRoute: MainStoreStockReportRoute,
  MainStoreTransferHistoryRoute: MainStoreTransferHistoryRoute,
}

const MainStoreRouteRouteWithChildren = MainStoreRouteRoute._addFileChildren(
  MainStoreRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainStoreRouteRoute: typeof MainStoreRouteRouteWithChildren
  MainCashierRoute: typeof MainCashierRoute
  MainNotificationsRoute: typeof MainNotificationsRoute
  MainProfileRoute: typeof MainProfileRoute
  MainIndexRoute: typeof MainIndexRoute
  MainCustomersCustomerIdRoute: typeof MainCustomersCustomerIdRoute
  MainOrdersCustomerProfilesOrdersRoute: typeof MainOrdersCustomerProfilesOrdersRoute
  MainOrdersNewAlterationOrderRoute: typeof MainOrdersNewAlterationOrderRoute
  MainOrdersNewSalesOrderRoute: typeof MainOrdersNewSalesOrderRoute
  MainOrdersNewWorkOrderRoute: typeof MainOrdersNewWorkOrderRoute
  MainOrdersOrderHistoryRoute: typeof MainOrdersOrderHistoryRoute
  MainOrdersOrdersAtShowroomRoute: typeof MainOrdersOrdersAtShowroomRoute
  MainAppointmentsIndexRoute: typeof MainAppointmentsIndexRoute
  MainCustomersIndexRoute: typeof MainCustomersIndexRoute
  MainOrdersOrderManagementAlterationsRoute: typeof MainOrdersOrderManagementAlterationsRoute
  MainOrdersOrderManagementBrovaFeedbackRoute: typeof MainOrdersOrderManagementBrovaFeedbackRoute
  MainOrdersOrderManagementCancelOrderRoute: typeof MainOrdersOrderManagementCancelOrderRoute
  MainOrdersOrderManagementChangeOptionsRoute: typeof MainOrdersOrderManagementChangeOptionsRoute
  MainOrdersOrderManagementDispatchRoute: typeof MainOrdersOrderManagementDispatchRoute
  MainOrdersOrderManagementFinalFeedbackRoute: typeof MainOrdersOrderManagementFinalFeedbackRoute
  MainOrdersOrderManagementLinkRoute: typeof MainOrdersOrderManagementLinkRoute
  MainOrdersOrderManagementReceivingBrovaFinalRoute: typeof MainOrdersOrderManagementReceivingBrovaFinalRoute
  MainOrdersOrderManagementUnlinkRoute: typeof MainOrdersOrderManagementUnlinkRoute
  MainOrdersOrderManagementFeedbackOrderIdRoute: typeof MainOrdersOrderManagementFeedbackOrderIdRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainStoreRouteRoute: MainStoreRouteRouteWithChildren,
  MainCashierRoute: MainCashierRoute,
  MainNotificationsRoute: MainNotificationsRoute,
  MainProfileRoute: MainProfileRoute,
  MainIndexRoute: MainIndexRoute,
  MainCustomersCustomerIdRoute: MainCustomersCustomerIdRoute,
  MainOrdersCustomerProfilesOrdersRoute: MainOrdersCustomerProfilesOrdersRoute,
  MainOrdersNewAlterationOrderRoute: MainOrdersNewAlterationOrderRoute,
  MainOrdersNewSalesOrderRoute: MainOrdersNewSalesOrderRoute,
  MainOrdersNewWorkOrderRoute: MainOrdersNewWorkOrderRoute,
  MainOrdersOrderHistoryRoute: MainOrdersOrderHistoryRoute,
  MainOrdersOrdersAtShowroomRoute: MainOrdersOrdersAtShowroomRoute,
  MainAppointmentsIndexRoute: MainAppointmentsIndexRoute,
  MainCustomersIndexRoute: MainCustomersIndexRoute,
  MainOrdersOrderManagementAlterationsRoute:
    MainOrdersOrderManagementAlterationsRoute,
  MainOrdersOrderManagementBrovaFeedbackRoute:
    MainOrdersOrderManagementBrovaFeedbackRoute,
  MainOrdersOrderManagementCancelOrderRoute:
    MainOrdersOrderManagementCancelOrderRoute,
  MainOrdersOrderManagementChangeOptionsRoute:
    MainOrdersOrderManagementChangeOptionsRoute,
  MainOrdersOrderManagementDispatchRoute:
    MainOrdersOrderManagementDispatchRoute,
  MainOrdersOrderManagementFinalFeedbackRoute:
    MainOrdersOrderManagementFinalFeedbackRoute,
  MainOrdersOrderManagementLinkRoute: MainOrdersOrderManagementLinkRoute,
  MainOrdersOrderManagementReceivingBrovaFinalRoute:
    MainOrdersOrderManagementReceivingBrovaFinalRoute,
  MainOrdersOrderManagementUnlinkRoute: MainOrdersOrderManagementUnlinkRoute,
  MainOrdersOrderManagementFeedbackOrderIdRoute:
    MainOrdersOrderManagementFeedbackOrderIdRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CashierRoute: CashierRoute,
  HomeRoute: HomeRoute,
  authLoginRoute: authLoginRoute,
  authErthLoginRoute: authErthLoginRoute,
  authSakkbaLoginRoute: authSakkbaLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
