-- Notification system: department-scoped notifications with per-user read tracking.
-- Notifications are generated by DB triggers on garment and transfer events.

-- 1. Create notification_type enum
CREATE TYPE notification_type AS ENUM (
    'garment_dispatched_to_workshop',
    'garment_dispatched_to_shop',
    'garment_ready_for_pickup',
    'garment_awaiting_trial',
    'transfer_requested',
    'transfer_status_changed'
);

-- 2. Create notifications table
CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    department department NOT NULL,
    type notification_type NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
    expires_at TIMESTAMP DEFAULT (now() + interval '7 days') NOT NULL
);

CREATE INDEX notifications_dept_created_idx ON notifications (department, created_at DESC);
CREATE INDEX notifications_expires_idx ON notifications (expires_at);

-- 3. Create notification_reads table (per-user read tracking)
CREATE TABLE notification_reads (
    notification_id INTEGER NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    read_at TIMESTAMP DEFAULT now() NOT NULL,
    PRIMARY KEY (notification_id, user_id)
);

-- 4. Enable RLS
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_reads ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies

-- Notifications: users can only see notifications for their department that haven't expired
CREATE POLICY "Users can view own department notifications"
    ON notifications FOR SELECT
    TO authenticated
    USING (department = get_my_department()::department AND expires_at > now());

-- Notification reads: users can only manage their own read records
CREATE POLICY "Users can view own reads"
    ON notification_reads FOR SELECT
    TO authenticated
    USING (user_id = get_my_user_id());

CREATE POLICY "Users can mark as read"
    ON notification_reads FOR INSERT
    TO authenticated
    WITH CHECK (user_id = get_my_user_id());

CREATE POLICY "Users can unmark reads"
    ON notification_reads FOR DELETE
    TO authenticated
    USING (user_id = get_my_user_id());

-- 6. Enable Supabase Realtime for notifications
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
