export const BRAND_NAMES = {
  showroom: "erth",
  fromHome: "sakkba",
} as const;

export const ProductionStageLabels = {
  "order_at_shop": "Order At Shop",
  "sent_to_workshop": "Sent To Workshop",
  "order_at_workshop": "Order At Workshop",
  "waiting_cut": "Waiting Cut",
  "soaking": "Soaking",
  "cutting": "Cutting",
  "post_cutting": "Post Cutting",
  "sewing": "Sewing",
  "finishing": "Finishing",
  "ironing": "Ironing",
  "quality_check": "Quality Check",
  "waiting_for_acceptance": "Waiting For Acceptance",
  "brova_dispatched_to_shop": "Brova Dispatched to Shop",
  "final_dispatched_to_shop": "Final Dispatched to Shop",
  "brova_and_final_dispatched_to_shop": "Brova & Final Dispatched to Shop",
  "brova_at_shop": "Brova At Shop",
  "brova_accepted": "Brova Accepted",
  "brova_alteration": "Brova Alteration",
  "brova_repair_and_production": "Brova Repair & Production",
  "brova_alteration_and_production": "Brova Alteration & Production",
  "final_at_shop": "Final At Shop",
  "brova_and_final_at_shop": "Brova & Final At Shop",
  "order_collected": "Order Collected",
  "order_delivered": "Order Delivered",
  "redo": "Redo"
} as const;

export const PieceStageLabels = {
  "order_at_shop": "Garment At Shop",
  "sent_to_workshop": "Sent to Workshop",
  "order_at_workshop": "Garment At Workshop",
  "waiting_cut": "Waiting Cut",
  "soaking": "Soaking",
  "cutting": "Cutting",
  "post_cutting": "Post Cutting",
  "sewing": "Sewing",
  "finishing": "Finishing",
  "ironing": "Ironing",
  "quality_check": "Quality Check",
  "waiting_for_acceptance": "Waiting For Acceptance",
  "brova_dispatched_to_shop": "Brova Dispatched to Shop",
  "final_dispatched_to_shop": "Final Dispatched to Shop",
  "brova_at_shop": "Brova At Shop",
  "brova_collected": "Brova Collected",
  "brova_accepted": "Confirmed Brova At Shop",
  "brova_alteration": "Brova Alteration",
  "brova_repair_and_production": "Brova Repair",
  "brova_alteration_and_production": "Brova Alteration & Production",
  "final_at_shop": "Final At Shop",
  "order_collected": "Order Collected",
  "order_delivered": "Order Delivered",
  "redo": "Redo"
} as const;
